package com.mycompany.proyectouveg.enums.LoveLenguageAndAffection;
import com.mycompany.proyectouveg.interfaces.love_lenguage_and_affection;
public enum man_love_lenguage_and_affection implements love_lenguage_and_affection{
}
